project
3 type de resource
-travail (personne(developeur/techenicient))
-comsomable (licence...)
-cout ponctuel (fait de deplacement et autre cout)

1 macro planigne
2 autre type de document


reponce au sujec
+ prise iniciative


























